In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
dataset = pd.read_csv("placement.csv")
dataset.head(3)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25

In [3]:
x = dataset.iloc[:,:-1]
y = dataset["package"]
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, random_state=42 , test_size=0.2)

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [6]:
lr = LinearRegression()
lr.fit(x_train , y_train)
lr.score(x_test , y_test)*100 , lr.score(x_train , y_train)*100 , lr.score(x_test , y_test)*100-lr.score(x_train , y_train)*100

(77.30984312051673, 77.58339025733345, -0.27354713681671683)

In [7]:
dt = DecisionTreeRegressor()
dt.fit(x_train , y_train)
dt.score(x_test , y_test)*100 , dt.score(x_train , y_train)*100 , dt.score(x_test , y_test)*100-dt.score(x_train , y_train)*100

(52.19733481708333, 95.1559200955432, -42.958585278459864)

In [8]:
sv = SVR()
sv.fit(x_train , y_train)
sv.score(x_test , y_test)*100 , sv.score(x_train , y_train)*100 , sv.score(x_test , y_test)*100-sv.score(x_train , y_train)*100

(75.94945442913415, 78.16909319813372, -2.219638768999573)

In [10]:
from sklearn.ensemble import VotingRegressor
li = [("dt1",DecisionTreeRegressor()),("sv1",SVR()),("lr",LinearRegression())]
vr = VotingRegressor(li) #weights = [10,4,7]
vr.fit(x_train , y_train)
vr.score(x_test , y_test)*100 , vr.score(x_train , y_train)*100 , vr.score(x_test , y_test)*100-vr.score(x_train , y_train)*100

(75.16568331690884, 87.56852979319457, -12.402846476285731)

In [11]:
prd ={"dt":dt.predict(x_test),"svc":sv.predict(x_test),"lr": lr.predict(x_test),"vr":vr.predict(x_test)}
pd.DataFrame(prd)

          dt       svc        lr        vr
0   2.920000  2.745462  2.780313  2.815259
1   3.252500  3.111375  3.136352  3.166742
2   2.920000  3.186923  3.199521  3.102148
3   2.540000  2.407183  2.389819  2.445667
4   3.990000  3.603909  3.526847  3.706919
5   4.110000  3.864755  3.768035  3.914263
6   3.330000  3.145318  3.165065  3.213461
7   2.235000  2.544422  2.544868  2.441430
8   3.330000  3.159083  3.176550  3.221878
9   3.140000  3.560946  3.492392  3.397779
10  1.995000  1.861447  1.907444  1.921297
11  2.570000  2.367828  2.349621  2.429150
12  3.890000  3.787063  3.687639  3.788234
13  1.940000  2.724923  2.757343  2.474089
14  3.250000  3.539138  3.475164  3.421434
15  2.850000  3.007404  3.044471  2.967292
16  2.436667  2.344391  2.326651  2.369236
17  2.920000  3.193945  3.205263  3.106403
18  2.550000  2.174781  2.177344  2.300708
19  3.310000  3.331379  3.314372  3.318584
20  2.580000  2.465325  2.452987  2.499437
21  3.185000  2.858757  2.900907  2.981555
22  3.310000  3.338777  3.320115  3.322964
23  3.110000  2.830893  2.872195  2.937696
24  2.770000  3.361030  3.337342  3.156124
25  2.100000  2.195711  2.194572  2.163428
26  1.940000  2.069395  1.419326  1.809573
27  3.020000  2.684696  2.711403  2.805366
28  3.420000  3.166005  3.182293  3.256099
29  2.436667  2.344391  2.326651  2.369236
30  3.420000  3.843594  3.745064  3.669553
31  2.970000  2.916291  2.958333  2.948208
32  3.760000  3.781130  3.681896  3.741009
33  3.080000  2.934040  2.975561  2.996534
34  3.180000  2.582838  2.590809  2.784549
35  2.770000  3.375907  3.348827  3.164912
36  2.200000  2.485568  2.475958  2.387175
37  3.030000  3.039129  3.073184  3.047438
38  3.330000  4.107480  4.175757  3.871079
39  2.970000  2.916291  2.958333  2.948208